hold on;
p1 = plot( ...
    {{name}}.SECONDS, ...
    {{name}}.T_01, ...
    'Color', 'k',  ...
    'LineWidth', 1 ...
);
p2 = plot( ...
    {{name}}.SECONDS, ...
    {{name}}.T_02, ...
    '--', ...
    'Color', 'k', ...
    'LineWidth', 1 ...
);
title('A MATLAB Plot');
legend([p1, p2], 'Temperature 1', 'Temperature 2');
hold off
